[package]
name = "sidecar-logging"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "testlog"
path = "src/testlog/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
