apiVersion: v1
kind: Pod
metadata:
  name: logging
spec:
  containers:
  - image: docker.io/mrunalp/testlog:0.1
    name: testlog
    imagePullPolicy: IfNotPresent
    args:
    - testlog
    volumeMounts:
    - mountPath: /var/log/shared
      name: log-volume
  - image: docker.io/mrunalp/vector:latest
    name: vector
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /var/log/shared
      name: log-volume
  volumes:
  - name: log-volume
    emptyDir: {}
